import os
import sys
import json
from pathlib import Path
from typing import List, Dict

import streamlit as st
from dotenv import load_dotenv

# ======= Path setup so we can import from /src =======
ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
sys.path.append(str(SRC))

from static_analyzer import run_pylint  # noqa: F402
from ai_reviewer import review_code_with_ai, ai_fix_suggestions  # noqa: F402
from auto_fixer import apply_auto_fixes  # noqa: F402

# ======== Env & App Config ========
load_dotenv(ROOT / ".env")
load_dotenv(ROOT / "ui" / ".env")
st.set_page_config(page_title="AI Code Reviewer", page_icon="🤖", layout="wide")
st.title("AI-Powered Code Reviewer")
st.caption("Hybrid review = Static analysis (Pylint) + LLM feedback + optional auto-fixes")

# Warn if no API key set (AI suggestions will fail gracefully)
groq_key = os.getenv("GROQ_API_KEY")
gemini_key = os.getenv("GEMINI_API_KEY")
openai_key = os.getenv("OPENAI_API_KEY")
if not groq_key and not gemini_key and (not openai_key or openai_key == "REPLACE_WITH_A_NEW_OPENAI_API_KEY"):
    st.warning(
        "No AI API key found. "
        "Set GROQ_API_KEY (free), GEMINI_API_KEY, or OPENAI_API_KEY in your .env file for AI features."
    )

# ====== Initialize session state keys (for persistence across reruns) ======
for key, default in {
    "code_input": "",
    "last_lint_issues": [],
    "last_code": "",
    "last_display_name": "pasted_code.py",
    "ai_fix_md": "",
    "fixed_code": "",
    "applied_fixes": [],
}.items():
    if key not in st.session_state:
        st.session_state[key] = default

# ====== Sidebar: sample picker ======
st.sidebar.header("Samples")
sample_path = ROOT / "samples" / "example_code.py"
if sample_path.exists():
    if st.sidebar.button("Load sample: example_code.py", use_container_width=True):
        st.session_state["code_input"] = sample_path.read_text(encoding="utf-8")

# ====== Input area ======
st.subheader("1) Provide code")
col1, col2 = st.columns(2)  # gap param removed: not supported in older Streamlit

with col1:
    uploaded = st.file_uploader("Upload a .py file", type=["py"])
    if uploaded is not None:
        code_text = uploaded.read().decode("utf-8")
        st.session_state["code_input"] = code_text
        st.session_state["last_display_name"] = uploaded.name  # persist name immediately
        st.info(f"Loaded file: {uploaded.name}")

with col2:
    code_default = st.session_state.get("code_input", "")
    code_box = st.text_area("Or paste Python code here", value=code_default, height=300)

# Decide final source of code
code_to_review = code_box.strip() if code_box.strip() else st.session_state.get("code_input", "")

st.subheader("2) Run review")
run_btn = st.button("Review Code", type="primary", use_container_width=True)


# ====== Helpers ======
def compute_quality_score(issues: List[Dict]) -> int:
    """Compute a 0-100 quality score from a list of enriched pylint issues."""
    if not issues:
        return 100
    penalty = 0
    for it in issues:
        sev = (it.get("severity") or "minor").lower()
        if sev == "critical":
            penalty += 10
        elif sev == "major":
            penalty += 5
        else:
            penalty += 2
    return max(0, 100 - penalty)


def build_report_md(file_name: str, issues: List[Dict], ai_text: str, score: int) -> str:
    """Build a Markdown report from the review results."""
    lines = []
    lines.append(f"# AI Code Review Report - {file_name}\n")
    lines.append("Generated by **AI-Powered Code Reviewer** (Pylint + LLM)\n")
    lines.append(f"**Quality Score:** {score}/100\n")

    lines.append("## Lint Issues\n")
    if not issues:
        lines.append("_No issues found by Pylint._\n")
    else:
        lines.append("| Severity | Type | Line | Message | Quick Fix |\n|---|---|---:|---|---|\n")
        for it in issues:
            msg = (it.get("message", "") or "").replace("|", "\\|")
            qf = (it.get("quick_fix", "") or "").replace("|", "\\|")
            lines.append(
                f"| {it.get('severity', '')} | {it.get('type', '')} | "
                f"{it.get('line', '')} | {msg} | {qf} |"
            )
        lines.append("")

    lines.append("## AI Feedback\n")
    lines.append(ai_text or "_No AI feedback._")
    lines.append("")
    return "\n".join(lines)


# ====== Main Action: run full review ======
if run_btn:
    if not code_to_review:
        st.error("Please upload or paste some Python code.")
        st.stop()

    # Save temp code for pylint
    tmp_file = ROOT / "samples" / "_tmp_ui_review.py"
    tmp_file.write_text(code_to_review, encoding="utf-8")

    # Run pylint
    with st.spinner("Running Pylint..."):
        lint_issues = run_pylint(
            str(tmp_file),
            output_json=str(ROOT / "reviews" / "lint_report.json"),
        )

    # AI review
    with st.spinner("Getting AI review..."):
        try:
            ai_feedback = review_code_with_ai(code_to_review)
        except Exception as e:
            st.error(f"AI review failed: {e}")
            ai_feedback = ""

    # Score + report
    score = compute_quality_score(lint_issues)
    # Use the name persisted when the file was uploaded, or fall back to "pasted_code.py"
    display_name = st.session_state.get("last_display_name", "pasted_code.py")
    report_md = build_report_md(
        file_name=display_name,
        issues=lint_issues,
        ai_text=ai_feedback,
        score=score,
    )

    # Persist markdown report
    reviews_dir = ROOT / "reviews"
    reviews_dir.mkdir(parents=True, exist_ok=True)
    (reviews_dir / "code_review_report.md").write_text(report_md, encoding="utf-8")

    # --- Persist essentials in session state for Fixes buttons ---
    st.session_state["last_lint_issues"] = lint_issues
    st.session_state["last_code"] = code_to_review
    # Clear previous fixes on each new run
    st.session_state["ai_fix_md"] = ""
    st.session_state["fixed_code"] = ""
    st.session_state["applied_fixes"] = []

    st.success("Review complete! See results below.")

    # ====== Results ======
    top_cols = st.columns(3)
    with top_cols[0]:
        st.metric(label="Quality Score", value=f"{score}/100")
    with top_cols[1]:
        st.metric(label="Pylint Issues", value=str(len(lint_issues)))
    with top_cols[2]:
        st.metric(label="AI Feedback", value="Ready" if ai_feedback else "Unavailable")

    st.subheader("Lint Issues")
    if lint_issues:
        st.dataframe(
            [
                {
                    "severity": it.get("severity", ""),
                    "type": it.get("type", ""),
                    "line": it.get("line", ""),
                    "message": it.get("message", ""),
                    "quick_fix": it.get("quick_fix", ""),
                    "symbol": it.get("symbol", ""),
                }
                for it in lint_issues
            ],
            use_container_width=True,
        )
    else:
        st.info("No lint issues found.")

    st.subheader("AI Feedback")
    st.markdown(ai_feedback if ai_feedback else "_No AI feedback._")

    st.subheader("Download")
    st.download_button(
        label="Download Markdown report",
        data=report_md.encode("utf-8"),
        file_name="code_review_report.md",
        mime="text/markdown",
        use_container_width=True,
    )
    st.download_button(
        label="Download raw lint JSON",
        data=json.dumps(lint_issues, indent=2).encode("utf-8"),
        file_name="lint_report.json",  # fixed: was "lint_repost.json"
        mime="application/json",
        use_container_width=True,
    )

# ====== Fixes section (persists via session_state) ======
st.subheader("3) Fixes")
c1, c2 = st.columns(2)

issues_source: List[Dict] = st.session_state.get("last_lint_issues", [])
code_source: str = st.session_state.get("last_code", code_to_review)
display_name_source: str = st.session_state.get("last_display_name", "pasted_code.py")

with c1:
    if st.button("Generate AI Fix Suggestion", use_container_width=True):
        if not code_source:
            st.error("Run a review first, then request AI fix suggestions.")
        else:
            with st.spinner("Asking AI for fix suggestions..."):
                try:
                    st.session_state["ai_fix_md"] = ai_fix_suggestions(code_source, issues_source)
                except Exception as e:
                    st.session_state["ai_fix_md"] = f"AI suggestions failed: {e}"

    if st.session_state["ai_fix_md"]:
        st.markdown(st.session_state["ai_fix_md"])

with c2:
    if st.button("Show Auto-Fixed Code (safe)", use_container_width=True):
        if not code_source:
            st.error("Run a review first, then show auto-fixed code.")
        else:
            with st.spinner("Applying auto-fixes..."):
                try:
                    fixed_code, applied_fixes = apply_auto_fixes(code_source, issues_source)
                    st.session_state["fixed_code"] = fixed_code
                    st.session_state["applied_fixes"] = applied_fixes
                except Exception as e:
                    st.error(f"Auto-fix failed: {e}")

    if st.session_state["fixed_code"]:
        st.subheader("Fixed Code")
        st.code(st.session_state["fixed_code"], language="python")
        if st.session_state["applied_fixes"]:
            st.info("Applied fixes:\n- " + "\n- ".join(st.session_state["applied_fixes"]))
        else:
            st.info("No safe auto-fixes were applied.")
        st.download_button(
            label="Download Fixed Code",
            data=st.session_state["fixed_code"].encode("utf-8"),
            file_name=display_name_source.replace(".py", "_fixed.py"),
            mime="text/x-python",
            use_container_width=True,
        )
